chatbot:
  log_dir_path: "./logs"
  chatbot_log_file_path: "chatbot.log"
  chat_history_limit: 5

main:
  log_dir_path: "./logs"
  main_log_file_path: "main.log"

workbench_params:
  log_dir_path: "./logs"
  workbench_logs_file_path: "workbench.log"

