chatbot:
  log_dir_path: "./logs"
  chatbot_log_file_path: "chatbot.log"
  chat_history_limit: 5

main:
  log_dir_path: "./logs"
  main_log_file_path: "main.log"
  chat_logs_file_path: "./data/chat_logs.csv"

sqlite_params:
  log_dir_path: "./logs"
  db_logs_file_path: "sqlite.log"
  db_path: "./data/chat_history.db"
  output_limit: 250

